name: Run Docker Compose

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "./docker/docker-compose.yml"
