name: Run Database Migrations and Docker

on:
  push:
    branches:
      - main
      - master

jobs:
  migrate_and_run_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1' # Adjust to match your Ruby version

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Database Migrations
        run: bundle exec rake db:migrate

      - name: Build Docker Image
        run: docker build -t inferno .

      - name: Run Docker Container
        run: docker run inferno
